### ISSUE TITLE
Help with getting some assets from Dungeon Assault?

### ISSUE THREAD

**Issue by bluewave41** [alterorb/launcher#4]
Hello! This isn't an issue and I know it's a longshot but I wanted to see if you could possibly help me in some way.

I've been wanting to rip the assets from Dungeon Assault but I've run into a lot of problems. The cache files are in a strange format and none of the available cache extractors have worked for me. Once I thought about it I figured the character previews would probably be animation files and that would be useless for me a I just want still images or any random frame.

Then I figured maybe I could memory edit myself into either the stable menu or change the previews in the tutorial which was well above my skill level.

My final hope was maybe I can use the API https://github.com/alterorb/http-api and make some changes to get into the stable menu and take a screencap of each character but it seems to be either incomplete or I'm doing something horribly wrong because running go run main.go results in

.\main.go:17:2: undefined: RegisterAccountEndpoints
.\main.go:18:2: undefined: RegisterSwaggerEndpoints
.\main.go:19:2: undefined: RegisterGamesEndpoints
.\main.go:20:2: undefined: RegisterHighscoresEndpoints

I'm not a go developer and I'm complete stuck now. Anything you might be able to offer to help me would be appreciated.

**Comment by hex-agon** [comment]
This api is only used to expose alterorb specific information, to dump assets from the cache you need something else. Join the funorb discord (invite link available at [alterorb's](https://alterorb.net) homepage), we'll help you there :)
