### ISSUE TITLE
How does it work, any documentation?

### ISSUE THREAD

**Issue by Kreijstal** [alterorb/launcher#5]
This is amazing!
You should explain how it works.

**Comment by hex-agon** [comment]
There's no documentation besides what's publicly available on this repository/org as code.

**Comment by Kreijstal** [comment]
Ohh, shouldn't we document it, for future proofing?

**Comment by hex-agon** [comment]
I don't really have much time any more to devote, and documenting is a high effort task, specially since the launcher is just the tip of the iceberg. Most of the concepts used in runescape private servers can be applied to the FunOrb games, and there's a lot of information around those.

**Comment by Kreijstal** [comment]
I created `alterorb-launcher-3.1.1.jar` so uh, how do you run it?

```
$ java -jar alterorb-launcher-3.1.1.jar
no main manifest attribute, in alterorb-launcher-3.1.1.jar
```

**Comment by Frosty-J** [comment]
How did you build it? Did you follow the Maven instructions? Because it should have a manifest if you've done it correctly.

If you just want to run it, download a release build.

**Comment by Kreijstal** [comment]
> How did you build it? Did you follow the Maven instructions? Because it should have a manifest if you've done it correctly.
> 
> If you just want to run it, download a release build.

I used `mvn package`
Jdk 21

**Comment by shadow-absorber** [comment]
> > How did you build it? Did you follow the Maven instructions? Because it should have a manifest if you've done it correctly.
> > If you just want to run it, download a release build.
> 
> I used `mvn package` Jdk 21
> 
> I don't want to just run it, I want to start work in dumping assets.
> 
> The magic word is: `java -cp "target/modules/*" net.alterorb.launcher.Bootstrap` after a `mvn package`

had similar problem wondering how to launch it and your comment here made shadow able to launch the launcher and play games for nostaliga
